#!/bin/bash

# script to delete all ApiDefinition and OperatorContexts from a namespace.

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:$PATH

if [[ $# -lt 1 ]]; then
	echo "[FATAL]Must provide namespace"
	exit 1
fi

typeset API
typeset OC
for NAMESPACE in $*; do
	# clean up the APIs first
	echo "[INFO]Deleting defined ApiDefinitions from $NAMESPACE"
	for API in $(kubectl get ApiDefinition -n $NAMESPACE --no-headers=true | awk '{print $1}'); do
		# have to remove the API finalizer to stop the namespace delete hanging
		kubectl get ApiDefinition $API -n $NAMESPACE -o yaml | yq 'del(.metadata.finalizers[])' | kubectl apply -f -
	done
	echo "[INFO]kubectl delete ApiDefinition all -n $NAMESPACE"
	kubectl delete ApiDefinition --all -n $NAMESPACE
	# delete OperatorContext finalizer since it can hang too
	sleep 1
	echo "[INFO]Deleting defined OperatorContext from $NAMESPACE"
	for OC in $(kubectl get OperatorContext -n $NAMESPACE --no-headers=true | awk '{print $1}'); do
		# have to remove the OperatorContext finalizer to stop the namespace delete hanging
		kubectl get OperatorContext $OC -n $NAMESPACE -o yaml | yq 'del(.metadata.finalizers[])' | kubectl apply -f -
		sleep 1
		echo "[INFO]kubectl delete OperatorContext $OC -n $NAMESPACE"
		kubectl delete OperatorContext $OC -n $NAMESPACE
	done
done
