#!/bin/bash

# script to delete all ApiDefinition and OperatorContexts from a namespace.

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:$PATH

if [[ $# -lt 1 ]]; then
	echo "[FATAL]Must provide namespace"
	exit 1
fi

typeset API
typeset OC
for NAMESPACE in $*; do
  # delete Portal Catalogues
  for CRD in portalapicatalogues apidescription securitypolicies subgraphs supergraphs ApiDefinition TykOasApiDefinition tykstreamsapidefinitions portalconfigs; do
    for item in $(kubectl get $CRD -n $NAMESPACE --no-headers=true 2>&- | awk '{print $1}'); do
		  kubectl get $CRD $item -n $NAMESPACE -o yaml | yq 'del(.metadata.finalizers[])' | kubectl apply -f -
		  kubectl get $CRD $item -n $NAMESPACE -o yaml | yq 'del(.metadata.finalizers)' | kubectl apply -f -
	  done
    sleep 1
  done

  for CRD in portalapicatalogues apidescription securitypolicies subgraphs supergraphs ApiDefinition TykOasApiDefinition tykstreamsapidefinitions portalconfigs; do
	  kubectl delete $CRD --all -n $NAMESPACE
  done

	# delete OperatorContext finalizer since it can hang too
	for OC in $(kubectl get OperatorContext -n $NAMESPACE --no-headers=true 2>&- | awk '{print $1}'); do
		kubectl get OperatorContext $OC -n $NAMESPACE -o yaml | yq 'del(.metadata.finalizers[])' | kubectl apply -f -
		kubectl get OperatorContext $OC -n $NAMESPACE -o yaml | yq 'del(.metadata.finalizers)' | kubectl apply -f -
	done
  sleep 1
	kubectl delete OperatorContext --all -n $NAMESPACE

	# now check results
  for CRD in portalapicatalogues apidescription securitypolicies subgraphs supergraphs ApiDefinition TykOasApiDefinition tykstreamsapidefinitions portalconfigs; do
	  echo "[INFO]Checking $CRD from $NAMESPACE to see if the finalizer is gone"
	  for item in $(kubectl get $CRD -n $NAMESPACE --no-headers=true | awk '{print $1}'); do
		  echo $item $(kubectl get $CRD $item -n $NAMESPACE -o yaml | yq .metadata.finalizers)
	  done
	done
done
