apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin
spec:
  contextRef:
    name: local-operator-context
    namespace: hsandbox-1
  name: httpbin
  use_keyless: true
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin.org/anything
    listen_path: /httpbin/
    strip_listen_path: true
