apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos
  labels:
    app: centos
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
      annotations:
    spec:
      containers:
      - image: centos:7
        imagePullPolicy: IfNotPresent
        name: centos
        securityContext:
          runAsNonRoot: false
          allowPrivilegeEscalation: true
          privileged: true
        command: ["/usr/bin/sleep", "infinity"]
        workingDir: /
