apiVersion: v1
kind: Service
metadata:
  name: edge-redis
  labels:
    app: redis
    plane: edge
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  type: NodePort
  selector:
    app: redis
    plane: edge
