apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-plugin
  labels:
    app: grpc-plugin
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: grpc-plugin
  template:
    metadata:
      labels:
        app: grpc-plugin
      annotations:
    spec:
      containers:
      - image: tyk-grpc:latest
        imagePullPolicy: Never
        name: grpc-plugin
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          capabilities:
            drop:
              - all
        command: ["/grpc_plugin"]
        workingDir: /
        ports:
        - containerPort: 9999
        livenessProbe:
          tcpSocket:
            port: 9999
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        readinessProbe:
          tcpSocket:
            port: 9999
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
