apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: ${KSBX_NS}-mongo-pvc
  labels:
    app: mongo
    plane: control
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongo-db
  labels:
    app: mongo
    plane: control
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
        plane: control
    spec:
      volumes:
        - name: mongo-db-vol
          persistentVolumeClaim:
            claimName: ${KSBX_NS}-mongo-pvc
      containers:
      - name: master
        image: mongo:4.4.17
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: /data/db
            name: mongo-db-vol

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
    app: mongo
    plane: control
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  type: NodePort
  selector:
    app: mongo
