apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
    app: mongo
    plane: control
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  type: NodePort
  selector:
    app: mongo
