---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${KSBX_NS}-mongo-pv
  labels:
    app: mongo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /home/docker/mongo/$KSBX_NS
  persistentVolumeReclaimPolicy: Delete

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv
  labels:
    app: mongo
spec:
  #storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongo-db
  labels:
    app: mongo      
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: master
        image: mongo:4.4.17
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: /data/db
            name: mongo-db-vol
      volumes:
        - name: mongo-db-vol
          persistentVolumeClaim:
            claimName: mongo-pv

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
    app: mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  type: NodePort
  selector:
    app: mongo
