apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: ${KSBX_NS}-mongo-pvc
  labels:
    app: mongo
    plane: control
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${KSBX_PG_MNGO_DB_SIZE}Gi
