---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongo-db
  labels:
    app: mongo      
spec:
  selector:
    matchLabels:
      app: mongo
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: mongo:4.4.17
        resources:
          requests:
            cpu: 500m
            memory: 1000Mi
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
    app: mongo
    role: master
    tier: backend
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  type: NodePort
  selector:
    app: mongo
    role: master
    tier: backend
