apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongo-db
  labels:
    app: mongo
    plane: control
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
        plane: control
    spec:
      volumes:
        - name: mongo-db-vol
          persistentVolumeClaim:
            claimName: ${KSBX_NS}-mongo-pvc
      containers:
      - name: master
        image: mongo:4.4.29
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: /data/db
            name: mongo-db-vol
