apiVersion: apps/v1 
kind: Deployment
metadata:
  name: postgres-db
  labels:
    app: postgres
    plane: control
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        plane: control
    spec:
      volumes:
        - name: postgres-db-vol
          persistentVolumeClaim:
            claimName: ${KSBX_NS}-postgres-pvc
      containers:
      - name: master
        image: postgres:latest
        env:
          - name: POSTGRES_DB
            value: ${KSBX_PGDB}
          - name: POSTGRES_USER
            value: ${KSBX_PGUSER}
          - name: POSTGRES_PASSWORD
            value: ${KSBX_PGPASSWORD}
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-db-vol
