apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    app: postgres
    plane: control
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  type: NodePort
  selector:
    app: postgres
