apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: ${KSBX_NS}-hybrid-redis-pvc
  labels:
    app: redis
    plane: hybrid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${KSBX_REDIS_DB_SIZE}Gi
