apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: ${KSBX_NS}-control-redis-pvc
  labels:
    app: redis
    plane: control
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-redis
  labels:
    app: redis
    plane: control
spec:
  selector:
    matchLabels:
      app: redis
      plane: control
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        plane: control
    spec:
      volumes:
        - name: control-redis-vol
          persistentVolumeClaim:
            claimName: ${KSBX_NS}-control-redis-pvc
      containers:
      - name: master
        image: redis:5.0.3
        command: ["redis-server", "--save 10 1"]
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: /data
            name: control-redis-vol

---
apiVersion: v1
kind: Service
metadata:
  name: control-redis
  labels:
    app: redis
    plane: control
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  type: NodePort
  selector:
    app: redis
    plane: control
