apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: ${KSBX_NS}-control-redis-pvc
  labels:
    app: redis
    plane: control
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${KSBX_REDIS_DB_SIZE}Gi
