---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: tbi
  labels:
    app: tbi
spec:
  selector:
    matchLabels:
      app: tbi
  replicas: 1
  template:
    metadata:
      labels:
        app: tbi
    spec:
      containers:
        - image: tbi:latest
          name: tbi
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
