apiVersion: v1
kind: ConfigMap
metadata:
  name: tyk-mdcb-conf
  labels:
    app: tyk-sink
    plane: control
data:
  tyk_sink.conf: |-
    {
      "aggregates_ignore_tags": [],
      "analytics": {
        "mongo_url": "mongodb://mongo-db/tyk_analytics"
      },
      "forward_analytics_to_pump": true,
      "hash_keys": false,
      "healthcheck_port": 8181,
      "license": "$KSBX_MDCB_LICENSE",
      "listen_port": 9090,
      "security": {
        "private_certificate_encoding_secret": "Secret"
      },
      "server_options": {
        "certificate": {
          "cert_file": "",
          "key_file": ""
        },
        "min_version": 771,
        "use_ssl": false
      },
      "storage": {
        "enable_cluster": false,
        "host": "control-redis",
        "port": 6379,
        "type": "redis"
      },
      "sync_worker_config": {
        "enabled": true,
        "hash_keys": false
      }
    }
