apiVersion: v1
kind: ConfigMap
metadata:
  name: tyk-pump-conf
  labels:
    app: tyk-pump
data:
  pump.conf: |-
    {
      "analytics_storage_type": "redis",
      "analytics_storage_config": { 
        "type": "redis",
        "host": "redis-db",
        "port": 6379,
        "hosts": null,
        "username": "",
        "password": "",
        "database": 0,
        "optimisation_max_idle": 10,
        "optimisation_max_active": 10,
        "enable_cluster": false
      },
      "purge_delay": 2,
      "pumps": { 
        "mongo": { 
          "type": "mongo",
          "meta": { 
            "collection_name": "tyk_analytics",
            "mongo_url": "mongodb://mongo-db/tyk_analytics",
            "collection_cap_enable": true,
            "collection_cap_max_size_bytes": 1048576,
            "max_insert_batch_size_bytes": 80000,
            "max_document_size_bytes": 20112
          }
        },
        "mongo-pump-aggregate": { 
          "type": "mongo-pump-aggregate",
          "meta": { 
            "mongo_url": "mongodb://mongo-db/tyk_analytics",
            "track_all_paths": true,
            "use_mixed_collection": true
          }
        }
      },
      "uptime_pump_config": { 
        "collection_name": "tyk_uptime_analytics",
        "mongo_url": "mongodb://mongo-db/tyk_analytics",
        "collection_cap_enable": true,
        "collection_cap_max_size_bytes": 1048576,
        "max_insert_batch_size_bytes": 500000,
        "max_document_size_bytes": 200000
      },
      "dont_purge_uptime_data": false,
      "health_check_endpoint_port": 8083
    }
