kind: Service
apiVersion: v1
metadata:
  name: tyk-portal
  labels:
    app: tyk-portal
    plane: control
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  type: NodePort
  selector:
    app: tyk-portal
    plane: control
