apiVersion: v1
kind: ConfigMap
metadata:
  name: tyk-gateway-conf
  labels:
    app: tyk-gateway
data:
  tyk_gateway.conf: |-
    {
        "listen_port": 8080,
        "secret": "12345",
        "node_secret": "352d20ee67be67f6340b4c0605b044b7",
        "template_path": "/opt/tyk-gateway/templates",
        "tyk_js_path": "/opt/tyk-gateway/js/tyk.js",
        "middleware_path": "/mnt/tyk-gateway/middleware",
        "use_db_app_configs": true,
        "db_app_conf_options": {
            "connection_string": "http://tyk-dashboard:3000",
            "node_is_segmented": false,
            "tags": []
        },
        "app_path": "/mnt/tyk-gateway/apps",
        "storage": {
            "type": "redis",
            "enable_cluster": false,
            "hosts": {
                "redis-db": "6379"
            },
            "username": "",
            "password": "",
            "database": 0,
            "optimisation_max_idle": 5000
        },
        "enable_analytics": true,
        "analytics_config": {
            "type": "mongo",
            "csv_dir": "/tmp",
            "mongo_url": "",
            "mongo_db_name": "",
            "mongo_collection": "",
            "purge_delay": -1,
            "ignored_ips": [],
            "normalise_urls": {
            "enabled": true,
            "normalise_uuids": true,
            "normalise_numbers": true
            }
        },
        "health_check": {
            "enable_health_checks": false,
            "health_check_value_timeouts": 60
        },
        "optimisations_use_async_session_write": true,
        "enable_non_transactional_rate_limiter": true,
        "enable_sentinel_rate_limiter": false,
        "allow_master_keys": false,
        "policies": {
            "policy_source": "service",
            "policy_connection_string": "http://tyk-dashboard:3000",
            "policy_record_name": "tyk_policies",
            "allow_explicit_policy_id": true
        },
        "hash_keys": true,
        "hash_key_function": "murmur128",
        "close_connections": false,
        "http_server_options": {
            "read_timeout": 0,
            "write_timeout": 0,
            "enable_websockets": true,
            "use_ssl": false,
            "use_ssl_le": false,
            "server_name": "*",
            "min_version": 0,
            "flush_interval":0
        },
        "uptime_tests": {
            "disable": true,
            "config": {
                "failure_trigger_sample_size": 1,
                "time_wait": 2,
                "checker_pool_size": 50,
                "enable_uptime_analytics": true
            }
        },
        "hide_generator_header": false,
        "allow_insecure_configs": true,
        "allow_remote_config": true,
        "coprocess_options": {
            "enable_coprocess": false
        },
        "enable_hashed_keys_listing": true,
        "suppress_redis_signal_reload": false,
        "enable_bundle_downloader": false,
        "use_redis_log": true,
        "use_sentry": false,
        "use_syslog": false,
        "use_logstash": false,
        "bundle_base_url": "",
        "global_session_lifetime": 100,
        "force_global_session_lifetime": false,
        "max_idle_connections_per_host": 500,
        "enable_custom_domains": true,
        "disable_dashboard_zeroconf": false,
        "enforce_org_data_age": true,
        "enforce_org_data_detail_logging": false,
        "enforce_org_quotas": true,
        "drl_enable_sentinel_rate_limiter": false,
        "oauth_refresh_token_expire": 0,
        "oauth_token_expire": 0,
        "track_404_logs": true,
        "oauth_redirect_uri_separator": ";",
        "pid_file_location": "/tmp/tyk-gateway.pid",
        "log_level": "info"
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyk-gateway
  labels:
    app: tyk-gateway
spec:
  replicas: 3
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: tyk-gateway
  template:
    metadata:
      labels:
        app: tyk-gateway
      annotations:
    spec:
      containers:
      - image: tykio/tyk-gateway:v4.0.0
        imagePullPolicy: IfNotPresent
        name: tyk-gateway
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          capabilities:
            drop:
              - all
        resources:
          limits:
            memory: 1Gi
            cpu: 1
          requests:
            memory: 512Mi
            cpu: 0.5
        env:
          - name: TYK_LOGLEVEL
            value: "debug"
        command: ["/opt/tyk-gateway/tyk", "--conf=/etc/tyk-gateway/tyk_gateway.conf"]
        workingDir: /opt/tyk-gateway
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: tyk-gateway-conf
            mountPath: /etc/tyk-gateway
        livenessProbe:
          httpGet:
            scheme: "HTTP"
            path: /hello
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        readinessProbe:
          httpGet:
            scheme: "HTTP"
            path: /hello
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
      volumes:
        - name: tyk-gateway-conf
          configMap:
            name: tyk-gateway-conf
            items:
              - key: tyk_gateway.conf
                path: tyk_gateway.conf
