apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyk-sink
  labels:
    app: tyk-sink
    plane: control
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: tyk-sink
      plane: control
  template:
    metadata:
      labels:
        app: tyk-sink
        plane: control
      annotations:
    spec:
      containers:
      - image: tykio/tyk-mdcb-docker:$KSBX_MDCB_VERS
        imagePullPolicy: IfNotPresent
        name: tyk-sink
        securityContext:
          runAsNonRoot: false
          allowPrivilegeEscalation: true
          privileged: true
        env:
          - name: TYK_MDCB_LOGLEVEL
            value: "debug"
        command: ["/opt/tyk-sink/tyk-sink", "-c", "/etc/tyk-sink/tyk_sink.conf"]
        workingDir: /opt/tyk-sink
        ports:
        - containerPort: 9090
        volumeMounts:
          - name: tyk-mdcb-conf
            mountPath: /etc/tyk-sink
        livenessProbe:
          httpGet:
            scheme: "HTTP"
            path: /health
            port: 8181
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        readinessProbe:
          httpGet:
            scheme: "HTTP"
            path: /health
            port: 8181
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
        - name: tyk-mdcb-conf
          configMap:
            name: tyk-mdcb-conf
            items:
              - key: tyk_sink.conf
                path: tyk_sink.conf
