apiVersion: v1
kind: ConfigMap
metadata:
  name: tyk-gateway-conf
  labels:
    app: tyk-gateway
data:
  tyk_gateway.conf: |-
    {
      "listen_address": "",
      "listen_port": 8080,
      "secret": "Secret",
      "node_secret": "shared_node_secret",
      "template_path": "/opt/tyk-gateway/templates",
      "tyk_js_path": "/opt/tyk-gateway/js/tyk.js",
      "middleware_path": "/opt/tyk-gateway/middleware",
      "policies": {
        "policy_source": "service",
        "policy_connection_string": "http://tyk-dashboard:3000",
        "policy_record_name": "tyk_policies",
        "allow_explicit_policy_id": true
      },
      "use_db_app_configs": true,
      "db_app_conf_options": {
        "connection_string": "http://tyk-dashboard:3000",
        "node_is_segmented": false,
        "tags": []
      },
      "disable_dashboard_zeroconf": true,
      "app_path": "/opt/tyk-gateway/test_apps/",
      "storage": {
        "type": "redis",
        "host": "redis-db",
        "port": 6379,
        "hosts": null,
        "username": "",
        "password": "",
        "database": 0,
        "optimisation_max_idle": 3000,
        "optimisation_max_active": 5000,
        "enable_cluster": false
      },
      "ssl_force_common_name_check": false,
      "enable_analytics": true,
      "analytics_config": {
        "enable_detailed_recording": true
      },
      "health_check": {
        "enable_health_checks": false,
        "health_check_value_timeouts": 60
      },
      "optimisations_use_async_session_write": true,
      "allow_master_keys": false,
      "hash_keys": false,
      "hash_key_function": "murmur64",
      "enable_hashed_keys_listing": true,
      "use_redis_log": true,
      "enforce_org_data_age": false,
      "enforce_org_data_detail_logging": false,
      "enforce_org_quotas": false,
      "experimental_process_org_off_thread": false,
      "enable_non_transactional_rate_limiter": true,
      "http_server_options": {
        "use_ssl": false,
        "ssl_insecure_skip_verify": true,
        "enable_websockets": true,
        "server_name": "",
        "min_version": 771,
        "prefer_server_ciphers": true,
        "flush_interval": 2
      },
      "close_connections": false,
      "uptime_tests": {
        "disable": false,
        "config": {
          "failure_trigger_sample_size": 3,
          "time_wait": 10,
          "checker_pool_size": 10,
          "enable_uptime_analytics": true
        }
      },
      "hostname": "",
      "control_api_hostname": "",
      "enable_custom_domains": true,
      "enable_jsvm": true,
      "hide_generator_header": false,
      "event_handlers": {
        "events": {}
      },
      "event_trigers_defunct": {},
      "pid_file_location": "/opt/tyk-gateway/tyk-gateway.pid",
      "allow_insecure_configs": true,
      "coprocess_options": {
        "enable_coprocess": true,
        "python_path_prefix": "/opt/tyk-gateway"
      },
      "dns_cache": {
        "enabled": true,
        "ttl": 60,
        "multiple_ips_handle_strategy": "random"
      },
      "proxy_ssl_insecure_skip_verify": true,
      "close_idle_connections": false,
      "allow_remote_config": false,
      "track_404_logs": true,
      "enable_bundle_downloader": false,
      "disable_ports_whitelist": true,
      "enable_http_profiler": true,
      "max_idle_connections_per_host": 50
    }
