apiVersion: v1
kind: ConfigMap
metadata:
  name: tyk-gateway-conf-standalone
  labels:
    app: tyk-gateway
    plane: control
data:
  tyk_gateway.conf: |-
    {
      "allow_insecure_configs": true,
      "allow_master_keys": false,
      "allow_remote_config": false,
      "analytics_config": {
        "enable_detailed_recording": true
      },
      "app_path": "/opt/tyk-gateway/apps/",
      "close_connections": false,
      "close_idle_connections": false,
      "control_api_hostname": "",
      "coprocess_options": {
        "enable_coprocess": true,
        "python_path_prefix": "/opt/tyk-gateway"
      },
      "disable_ports_whitelist": true,
      "dns_cache": {
        "enabled": true,
        "multiple_ips_handle_strategy": "random",
        "ttl": 60
      },
      "enable_analytics": true,
      "enable_bundle_downloader": false,
      "enable_custom_domains": true,
      "enable_hashed_keys_listing": true,
      "enable_http_profiler": true,
      "enable_jsvm": true,
      "enable_non_transactional_rate_limiter": true,
      "enforce_org_data_age": false,
      "enforce_org_data_detail_logging": false,
      "enforce_org_quotas": false,
      "event_handlers": {
        "events": {}
      },
      "event_trigers_defunct": {},
      "experimental_process_org_off_thread": false,
      "hash_key_function": "murmur64",
      "hash_keys": false,
      "health_check": {
        "enable_health_checks": false,
        "health_check_value_timeouts": 60
      },
      "hide_generator_header": false,
      "hostname": "",
      "http_server_options": {
        "enable_websockets": true,
        "flush_interval": 2,
        "min_version": 771,
        "prefer_server_ciphers": true,
        "server_name": "",
        "ssl_insecure_skip_verify": true,
        "use_ssl": false
      },
      "listen_address": "",
      "listen_port": 8080,
      "max_idle_connections_per_host": 50,
      "middleware_path": "/opt/tyk-gateway/middleware",
      "pid_file_location": "/opt/tyk-gateway/tyk-gateway.pid",
      "policies": {
        "policy_source": "file",
        "policy_path": "/opt/tyk-gateway/policies/"
      },
      "proxy_ssl_insecure_skip_verify": true,
      "secret": "Secret",
      "ssl_force_common_name_check": false,
      "storage": {
        "database": 0,
        "enable_cluster": false,
        "host": "control-redis",
        "hosts": null,
        "optimisation_max_active": 4000,
        "optimisation_max_idle": 2000,
        "password": "",
        "port": 6379,
        "type": "redis",
        "username": ""
      },
      "template_path": "/opt/tyk-gateway/templates",
      "track_404_logs": true,
      "tyk_js_path": "/opt/tyk-gateway/js/tyk.js",
      "uptime_tests": {
        "config": {
          "checker_pool_size": 10,
          "enable_uptime_analytics": true,
          "failure_trigger_sample_size": 3,
          "time_wait": 10
        },
        "disable": false
      },
      "use_db_app_configs": false,
      "use_redis_log": true
    }
