apiVersion: v1
kind: ConfigMap
metadata:
  name: tyk-portal-conf
  labels:
    app: tyk-portal
data:
  portal.conf: |-
    {
      "Blog": {
        "Enable": true
      },
      "Forms": {
        "Enable": true
      },
      "Site": {
        "Enable": true
      },
      "HostPort": 3001,
      "PortalAPISecret": "123456",
      "DisableCSRFCheck": true,
      "TLSConfig": {
        "InsecureSkipVerify": true
      }
    }

