kind: Service
apiVersion: v1
metadata:
  name: standalone-gateway
  labels:
    app: tyk-gateway
    plane: control
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: NodePort
  selector:
    app: tyk-gateway
    plane: control
